_DEFAULT_TEMPLATES = {
    "default": "%(title)s.%(ext)s",  # Default template, single videos
    "playlist": "%(playlist_title)s/%(playlist_index)s - %(title)s.%(ext)s",  # Playlist template
    "channel": "%(uploader)s/%(title)s.%(ext)s",  # Channel template
    "legacy_archive_default": "%(title)s - %(uploader)s - %(upload_date)s/%(uploader)s - %(upload_date)s [%(id)s].%(ext)s",  # Default legacy template for the archive mode
    "legacy_playlist": "'%(playlist_title)s/%(uploader)s/%(upload_date)s - %(title)s/%(upload_date)s [%(id)s].%(ext)s",  # Legacy playlist template using --yes-playlist in archive mode
    "legacy_no_playlist": "%(uploader)s/%(upload_date)s - %(title)s/%(upload_date)s [%(id)s].%(ext)s",  # Legacy playlist template using --no-playlist in archive mode
    "legacy_channel": "%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s/%(uploader)s - %(upload_date)s [%(id)s].%(ext)s",  # Legacy archive channel template for archive mode
}
_TEMPLATE_FIELDS = [
    "%(id)s",
    "%(title)s",
    "%(fulltitle)s",
    "%(ext)s",
    "%(alt_title)s",
    "%(description)s",
    "%(display_id)s",
    "%(uploader)s",
    "%(uploader_id)s",
    "%(uploader_url)s",
    "%(license)s",
    "%(creators)s",
    "%(creator)s",
    "%(timestamp)s",
    "%(upload_date)s",
    "%(release_timestamp)s",
    "%(release_date)s",
    "%(reupload_year)s",
    "%(modified_timestamp)s",
    "%(modified_date)s",
    "%(channel)s",
    "%(channel_id)s",
    "%(channel_url)s",
    "%(channel_follower_count)s",
    "%(channel_is_verified)s",
    "%(location)s",
    "%(duration)s",
    "%(duration_string)s",
    "%(view_count)s",
    "%(like_count)s",
    "%(dislike_count)s",
    "%(repost_count)s",
    "%(average_rating)s",
    "%(comment_count)s",
    "%(age_limit)s",
    "%(live_status)s",
    "%(is_live)s",
    "%(was_live)s",
    "%(playable_in_embed)s",
    "%(availability)s",
    "%(media_type)s",
    "%(start_time)s",
    "%(end_time)s",
    "%(extractor)s",
    "%(extractor_key)s",
    "%(epoch)s",
    "%(autonumber)s",
    "%(video_autonumber)s",
    "%(n_entries)s",
    "%(playlist_id)s",
    "%(playlist_title)s",
    "%(playlist)s",
    "%(playlist_count)s",
    "%(playlist_index)s",
    "%(playlist_auto_number)s",
    "%(playlist_uploader)s",
    "%(playlist_uploader_id)s",
    "%(webpage_url)s",
    "%(webpage_url_basename)s",
    "%(webpage_url_domain)s",
    "%(original_url)s",
    "%(categories)s",
    "%(tags)s",
    "%(cast)s",
]
